# Generated by Django 2.2 on 2019-09-07 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventFinderApp', '0002_event_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='catagory',
            field=models.ManyToManyField(to='eventFinderApp.Category'),
        ),
    ]
