# Generated by Django 2.2 on 2019-09-07 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventFinderApp', '0003_event_catagory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='catagory',
            new_name='category',
        ),
    ]
